name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-debian:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Build Tools
        run: |
          sudo apt update
          sudo apt install -y build-essential devscripts debhelper dh-python pybuild-plugin-pyproject python3-all python3-setuptools python3-build python3-installer python3-requests python3-bs4 python3-rich python3-cloudscraper python3-tqdm

      - name: Build Debian Package
        run: |
          dpkg-buildpackage -us -uc -b

      - name: Move artifacts
        run: mv ../ani-pull_*.deb .

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: "ani-pull_*.deb"

  build-rpm:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Build Tools
        run: |
          dnf install -y rpm-build python3-devel python3-setuptools pyproject-rpm-macros python3-build python3-installer tar \
                         python3-requests python3-beautifulsoup4 python3-rich python3-tqdm yt-dlp

      - name: Prepare Source Tarball
        run: |
          VERSION="1.1.0"
          mkdir -p rpmbuild/SOURCES
          tar --transform "s|^|ani-pull-${VERSION}/|" -czf rpmbuild/SOURCES/v${VERSION}.tar.gz --exclude=rpmbuild .

      - name: Build RPM
        run: |
          mkdir -p rpmbuild/{BUILD,RPMS,SRPMS,SPECS}
          cp packaging/fedora/ani-pull.spec rpmbuild/SPECS/
          rpmbuild --define "_topdir $(pwd)/rpmbuild" -ba rpmbuild/SPECS/ani-pull.spec

      - name: Move artifacts
        run: cp rpmbuild/RPMS/noarch/*.rpm .

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rpm-package
          path: "*.rpm"

  release:
    needs: [build-debian, build-rpm]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Debian package
        uses: actions/download-artifact@v4
        with:
          name: deb-package

      - name: Download RPM package
        uses: actions/download-artifact@v4
        with:
          name: rpm-package

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.deb
            *.rpm
          body: "Automated release for version ${{ github.ref_name }}"
