name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Build Tools
        run: |
          sudo apt update
          sudo apt install -y build-essential devscripts debhelper dh-python pybuild-plugin-pyproject python3-all python3-setuptools python3-build python3-installer python3-requests python3-bs4 python3-rich python3-cloudscraper python3-tqdm

      - name: Build Debian Package
        run: |
          dpkg-buildpackage -us -uc -b

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: "../ani-pull_*.deb"

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: deb-package

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.deb
          body: "Automated release for version ${{ github.ref_name }}"
